Attribute VB_Name = "Helpers_Intake"
Sub aggFlag(ByVal userRow As Long)
    Call flagNo(Range(hFind("Was Youth on Pretrial?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Was Youth on Consent Decree?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Was Youth on Interim Probation?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Was Youth on Probation?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Was Youth on Aftercare Probation?", "AGGREGATES") & userRow))

    Call flagNo(Range(hFind("Was Notice of Certification Given?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Was Notice of De-Certification Given?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Did Youth Enter an Admission?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Adjudicated Delinquent?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Did Youth Have a Continuance?", "AGGREGATES") & userRow))

    Call flagNo(Range(hFind("Was Youth Placed?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Did Youth Have Restitution?", "AGGREGATES") & userRow))

    Call flagNo(Range(hFind("Did Youth Have Court Costs?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Did Youth Have Comm. Service?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Was Youth Rearrested?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Did Youth FTA?", "AGGREGATES") & userRow))
    Call flagNo(Range(hFind("Record Expunged?", "AGGREGATES") & userRow))
End Sub

Sub courtsFlag(ByVal userRow As Long)
    Call flagNo(Range(hFind("Was Youth in 4G?") & userRow))
    Call flagNo(Range(hFind("Was Youth in 4E?") & userRow))
    Call flagNo(Range(hFind("Was Youth in 6F?") & userRow))
    Call flagNo(Range(hFind("Was Youth in 6H?") & userRow))
    Call flagNo(Range(hFind("Was Youth in 3E?") & userRow))
    Call flagNo(Range(hFind("Was Youth on Crossover Status?") & userRow))
    Call flagNo(Range(hFind("Was Youth on WRAP Status?") & userRow))
    Call flagNo(Range(hFind("Was Youth in JTC?") & userRow))
    Call flagNo(Range(hFind("Was Youth in Adult?") & userRow))
End Sub

Sub supervisionSectionFlag(ByVal userRow As Long, bucketHead As String)
    Call flagNo(Range(hFind("Did Youth Have IPS?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Did Youth Have Pre-ERC?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Did Youth Have IHD?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Did Youth Have ISP?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Did Youth Have GPS?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Did Youth Have Post-ERC?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Did Youth Have Reintegration?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Did Youth Have CUA?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Did Youth Have RTF?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Did Youth Have Inpatient D&A?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Did Youth Have Other Supervision?", bucketHead) & userRow))
End Sub

Sub conditionSectionFlag(ByVal userRow As Long, bucketHead As String)
    Call flagNo(Range(hFind("Was Youth Ordered Anger Mgt.?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Alternative School?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered a BHE?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Community Service?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered a Curfew?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Daily School?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Drug Screens?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Essay?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Family Therapy?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered GED?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Grief Counseling?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Mental Health?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Inpatient D&A?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered IOP?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Restitution?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Sexual Counseling?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Victim Conference?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered 1st Violation Hold?", bucketHead) & userRow))
    Call flagNo(Range(hFind("Was Youth Ordered Other Condition?", bucketHead) & userRow))
End Sub
